# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5bZ4fVR4M1LdQtTv8r1TBAlwKqQzDPj
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

sheet = pd.read_excel("/content/Regional Sales Dataset.xlsx",sheet_name = None)

sheet

df_sales = sheet['Sales Orders']
df_customers = sheet['Customers']
df_products = sheet['Products']
df_regions = sheet['Regions']
df_state_reg = sheet['State Regions']
df_Budget= sheet['2017 Budgets']

df_sales.isnull().sum()

# folder state reg making header proper
new_header = df_state_reg.iloc[0]
df_state_reg.columns = new_header
df_state_reg = df_state_reg[1:].reset_index()

# sales with customer

#merge
df = df_sales.merge(df_customers, how='left', left_on = 'Customer Name Index',right_on = 'Customer Index')

df.info()

# merge with products

df = df.merge(df_products, how='left', left_on = 'Product Description Index',right_on = 'Index')

# merge with Region

df = df.merge(df_regions, how='left', left_on = 'Delivery Region Index',right_on = 'id')

# merge with state code

df = df.merge(df_state_reg, how='left', left_on = 'state_code',right_on = 'State Code')

# merge with Budget

df = df.merge(df_Budget, how='left', on ='Product Name')

df.info()

# Cleaning Duplicates Col
col_to_drop = [
    'Customer Index','State Code','id','Index'
]

df= df.drop(columns=col_to_drop,errors ='ignore')

# convert col to lower case
df.columns = df.columns.str.lower()

df.columns

# Keeping col which is needed
col_to_keep = [
    'ordernumber','orderdate','customer names',
    'channel',
'product name',
'order quantity',
'unit price',
'line total',
'total unit cost',
'county',
'state',
'state_code',
'region',
'latitude',
'longitude',
'2017 budgets'
]

df = df[col_to_keep]

df['state']

df = df.rename(columns={
    'ordernumber': 'order_number',
    'orderdate': 'order_date',
    'customer names': 'customer_name',
    'product name': 'product_name',
    'order quantity': 'order_quantity',
    'unit price': 'unit_price',
    'line total': 'revenue',
    'total unit cost': 'total_unit_cost', # Corrected typo from 'total_unit_cost'
    'state_code': 'S_CODE',      # Rename state_code (e.g., 'AZ') to state_abbr
    'state': 'state_name',          # Rename the remaining 'state' (e.g., 'Arizona') to state_name
    'latitude': 'lat',
    'longitude': 'lon',
    '2017 budgets': 'budget'
})


df.head(2)

# blank out not 2017 data
df.loc[df['order_date'].dt.year != 2017, 'budget'] = pd.NA

df.head(2)

print(df[['order_date', 'order_number', 'budget']].sample(8))

df.to_csv('MAIN.csv', index=False)

#filter data with 2017 only
df_2017 = df[df['order_date'].dt.year == 2017]

df_2017.head(3)

df.info()

df = df.rename(columns={df.columns[10]: "state_name"})

df['total_cost'] =  df['order_quantity'] * df['total_unit_cost']

df['Profit'] = df['revenue'] - df['total_cost']

df['profit_margin'] = df['Profit'] /df['revenue'] * 100

df.head(5)

### EDA

df.columns

# 2. Create a Year-Month column
df['year_month'] = df['order_date'].dt.to_period('M')

# 3. Aggregate monthly sales
monthly_sales = (
    df.groupby('year_month')['revenue']
      .sum()
      .reset_index()
)

# 4. Convert period back to timestamp for plotting
monthly_sales['year_month'] = monthly_sales['year_month'].dt.to_timestamp()

# 5. Plot line chart
plt.figure(figsize=(12, 6))
plt.plot(monthly_sales['year_month'], monthly_sales['revenue'], marker='o')
plt.title('Monthly Sales Trend')
plt.xlabel('Month')
plt.ylabel('Total Sales (Revenue)')
plt.grid(True)
plt.tight_layout()
plt.show()

# Remove Jan & Feb 2018
df = df[~(
    (df['order_date'] >= '2018-01-01') &
    (df['order_date'] <  '2018-03-01')
)]

# 2. Extract month number and month name
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.month_name()

# 3. Aggregate across ALL years by month (use MEAN for seasonality)
monthly_seasonality = (
    df.groupby(['month', 'month_name'])['revenue']
      .sum()
      .reset_index()
      .sort_values('month')
)

# 4. Plot
plt.figure(figsize=(12, 6))
plt.plot(
    monthly_seasonality['month_name'],
    monthly_seasonality['revenue'],
    marker='o'
)

plt.title('Overall Monthly Sales Seasonality (All Years Combined)')
plt.xlabel('Month')
plt.ylabel('Average Monthly Sales')
plt.grid(True)
plt.tight_layout()
plt.show()

#May, August ,March has the highest sales & April, July, Feburay  has the lowest sales,
#pattern could  me every 2 month sales is down

top_10_products = (
    df.groupby('product_name')['revenue']
      .sum()
      .sort_values(ascending=False)
      .head(10)
      .reset_index()
)

# Plot
plt.figure(figsize=(12, 6))

ax = sns.barplot(
    data=top_10_products,
    x='product_name',
    y='revenue',
    palette='tab10'   # different color per bar
)

# Add data labels
for container in ax.containers:
    ax.bar_label(
        container,
        fmt='{:,.0f}',
        padding=3,
        fontsize=9
    )

# Titles and labels
ax.set_title('Top 10 Products by Revenue')
ax.set_xlabel('Product')
ax.set_ylabel('Total Revenue')

# Gridlines (Y-axis only)
ax.yaxis.grid(True, linestyle='--', alpha=0.7)
ax.xaxis.grid(False)

# Rotate x labels
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

# Aggregate revenue by product
bottom_10_products = (
    df.groupby('product_name')['revenue']
      .sum()
      .sort_values(ascending=True)   # ascending = bottom
      .head(10)
      .reset_index()
)

# Plot
plt.figure(figsize=(12, 6))

ax = sns.barplot(
    data=bottom_10_products,
    x='product_name',
    y='revenue',
    palette='tab10'
)

# Add data labels
for container in ax.containers:
    ax.bar_label(
        container,
        fmt='{:,.0f}',
        padding=3,
        fontsize=9
    )

# Titles and labels
ax.set_title('Bottom 10 Products by Revenue')
ax.set_xlabel('Product')
ax.set_ylabel('Total Revenue')

# Gridlines (Y-axis only)
ax.yaxis.grid(True, linestyle='--', alpha=0.7)
ax.xaxis.grid(False)

# Rotate x labels
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

## sales by channel
 # Aggregate revenue by channel
sales_by_channel = (
    df.groupby('channel')['revenue']
      .sum()
      .sort_values(ascending=False)
)

# Plot pie chart
plt.figure(figsize=(8,4))
plt.pie(
    sales_by_channel.values,
    labels=sales_by_channel.index,
    autopct='%1.1f%%',
    startangle=140
)

plt.title('Sales Distribution by Channel')
plt.tight_layout()
plt.show()

# Distribution of average order value
# Calculate AOV per order
aov_df = (
    df.groupby('order_number')['revenue']
      .sum()
      .reset_index(name='order_value')
)


plt.figure(figsize=(12, 6))

ax = sns.histplot(
    data=aov_df,
    x='order_value',
    bins=50,
    kde=True   # this adds the smooth flow line
)

# Titles and labels
ax.set_title('Distribution of Average Order Value (AOV)')
ax.set_xlabel('Order Value')
ax.set_ylabel('Number of Orders')

# Gridlines (Y-axis only)
ax.yaxis.grid(True, linestyle='--', alpha=0.7)
ax.xaxis.grid(False)

plt.tight_layout()
plt.show()

# Right skwe  - most order btw 20 to 100k ,max is around is 50-60k ,
#& Large order represent a small share of Profit Share

# Unit Price Distribution Per product
# State top 10 by revenue and order count
#Avg Profit Margin By Channel
#Top & Bottom 10 Customer by Revenue
#Customer Segmentation : Revenue  vs profit Margin
# Heat Map

plt.figure(figsize=(14, 6))

ax = sns.boxplot(
    data=df,
    x='product_name',
    y='unit_price'
)

ax.set_title('Unit Price Distribution per Product')
ax.set_xlabel('Product')
ax.set_ylabel('Unit Price')

plt.xticks(rotation=45, ha='right')
ax.yaxis.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""Products 8,17,27,20,28 show high end revenue spikes well above their upper whiskeres likely due to bulk orders"""

# Aggregate revenue by state
top_10_states_revenue = (
    df.groupby(df.iloc[:, 10])['revenue']
      .sum()
      .sort_values(ascending=False)
      .head(10)
      .reset_index()
)

plt.figure(figsize=(12, 6))

ax = sns.barplot(
    data=top_10_states_revenue,
     x='state_name',   # state_name is now unambiguous in top_10_states_revenue
    y='revenue',
    palette='tab10'
)

# Data labels
for container in ax.containers:
    ax.bar_label(container, fmt='{:,.0f}', padding=3)

ax.set_title('Top 10 States by Revenue')
ax.set_xlabel('State')
ax.set_ylabel('Total Revenue')

ax.yaxis.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

display(top_10_states_revenue)

"""california ,illinos,florida,texas new york"""

top_10_states_aov = (
    df.groupby(df.iloc[:, 10])['revenue']
      .sum()
      .sort_values(ascending=False)
      .tail(10)
      .reset_index(name='avg_order_value')
)

plt.figure(figsize=(12, 6))

ax = sns.barplot(
    data=top_10_states_aov,
    x='state_name',
    y='avg_order_value',
    palette='tab10'
)

# Data labels
for container in ax.containers:
    ax.bar_label(container, fmt='{:,.0f}', padding=3)

ax.set_title('Bottom 10 States by Order Value')
ax.set_xlabel('State')
ax.set_ylabel('Order Value')

ax.yaxis.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

# Average Profit Margin by Channel
# Aggregate average profit margin by channel
avg_profit_margin_channel = (
    df.groupby('channel')['profit_margin']
      .mean()
      .reset_index()
)

plt.figure(figsize=(8, 6))

ax = sns.barplot(
    data=avg_profit_margin_channel,
    x='channel',
    y='profit_margin',
    palette='tab10'
)

# Data labels (convert to % if margin is in fraction form)
for container in ax.containers:
    ax.bar_label(
        container,
        fmt='{:,.2f}',
        padding=3
    )

ax.set_title('Average Profit Margin by Channel')
ax.set_xlabel('Channel')
ax.set_ylabel('Average Profit Margin')

ax.yaxis.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

customer_revenue = (
    df.groupby('customer_name')['revenue']
      .sum()
      .reset_index()
)

top_10_customers = (
    customer_revenue
    .sort_values('revenue', ascending=False)
    .head(10)
)

bottom_10_customers = (
    customer_revenue
    .sort_values('revenue', ascending=True)
    .head(10)
)

blue_gradient = sns.color_palette("Blues", n_colors=10)
red_gradient = sns.color_palette("Reds", n_colors=10)

fig, axes = plt.subplots(1, 2, figsize=(18, 6))

# ---- Top 10 Customers (Blue gradient) ----
sns.barplot(
    data=top_10_customers,
    y='customer_name',
    x='revenue',
    ax=axes[0],
    palette=blue_gradient
)

axes[0].set_title('Top 10 Customers by Revenue')
axes[0].set_xlabel('Total Revenue')
axes[0].set_ylabel('Customer')
axes[0].xaxis.grid(True, linestyle='--', alpha=0.7)

for container in axes[0].containers:
    axes[0].bar_label(container, fmt='{:,.0f}', padding=3)


# ---- Bottom 10 Customers (Red gradient) ----
sns.barplot(
    data=bottom_10_customers,
    y='customer_name',
    x='revenue',
    ax=axes[1],
    palette=red_gradient
)

axes[1].set_title('Bottom 10 Customers by Revenue')
axes[1].set_xlabel('Total Revenue')
axes[1].set_ylabel('Customer')
axes[1].xaxis.grid(True, linestyle='--', alpha=0.7)

for container in axes[1].containers:
    axes[1].bar_label(container, fmt='{:,.0f}', padding=3)

plt.tight_layout()
plt.show()

"""top 10  Aibox ,state Ltd with 12-10 million usd
bottom 10 by 8817, yodoo ltd with 5-4 million usd
"""

df['profit_margin']

customer_metrics = (
    df.groupby('customer_name')
      .agg(
          total_revenue=('revenue', 'sum'),
          total_profit=('Profit', 'sum')
      )
      .reset_index()
)

# Weighted profit margin
customer_metrics['profit_margin'] = (
    customer_metrics['total_profit'] / customer_metrics['total_revenue']
)

plt.figure(figsize=(8, 4))

ax = sns.scatterplot(
    data=customer_metrics,
    x='total_revenue',
    y='profit_margin',
    alpha=0.7
)

ax.set_title('Customer Segmentation: Revenue vs Profit Margin')
ax.set_xlabel('Total Revenue')
ax.set_ylabel('Profit Margin')

# Reference lines
ax.axhline(0, linestyle='--', color='grey')
ax.axvline(0, linestyle='--', color='grey')

ax.yaxis.grid(True, linestyle='--', alpha=0.5)
ax.xaxis.grid(False)

plt.tight_layout()
plt.show()

from matplotlib.ticker import FuncFormatter
# Revenue formatter: Millions, no decimals
def revenue_millions(x, pos):
    return f'{int(x/1_000_000)}M'

# Profit margin formatter: Percentage, no decimals
def profit_margin_percent(y, pos):
    return f'{int(y * 100)}%'


plt.figure(figsize=(8, 4))

ax = sns.scatterplot(
    data=customer_metrics,
    x='total_revenue',
    y='profit_margin',
    alpha=0.7
)

ax.set_title('Customer Segmentation: Revenue vs Profit Margin')
ax.set_xlabel('Total Revenue (Millions)')
ax.set_ylabel('Profit Margin (%)')

# Apply formatters
ax.xaxis.set_major_formatter(FuncFormatter(revenue_millions))
ax.yaxis.set_major_formatter(FuncFormatter(profit_margin_percent))

# Reference lines
ax.axhline(0, linestyle='--', color='grey')
ax.axvline(0, linestyle='--', color='grey')

# Gridlines
ax.yaxis.grid(True, linestyle='--', alpha=0.5)
ax.xaxis.grid(False)

plt.tight_layout()
plt.show()

from matplotlib.ticker import FuncFormatter

# Means (unchanged)
rev_mean = customer_metrics['total_revenue'].mean()
margin_mean = customer_metrics['profit_margin'].mean()

# Axis formatters
def revenue_millions(x, pos):
    return f'{int(x / 1_000_000)}M'

def profit_margin_percent(y, pos):
    return f'{int(y * 100)}%'

plt.figure(figsize=(10, 6))

ax = sns.scatterplot(
    data=customer_metrics,
    x='total_revenue',
    y='profit_margin',
    alpha=0.7
)

# Quadrant lines (true values, not formatted)
ax.axvline(rev_mean, linestyle='--', color='black')
ax.axhline(margin_mean, linestyle='--', color='black')

ax.set_title('Customer Segmentation: Revenue vs Profit Margin')
ax.set_xlabel('Total Revenue (Millions)')
ax.set_ylabel('Profit Margin (%)')

# Apply formatters
ax.xaxis.set_major_formatter(FuncFormatter(revenue_millions))
ax.yaxis.set_major_formatter(FuncFormatter(profit_margin_percent))

# Gridlines
ax.yaxis.grid(True, linestyle='--', alpha=0.5)
ax.xaxis.grid(False)

plt.tight_layout()
plt.show()

"""1️⃣ Most customers sit near the middle

Majority are clustered around ₹5–8M revenue and 35–40% margin
👉 This is your average, stable customer base.

2️⃣ High revenue ≠ high margin

Several high-revenue customers (right side) have only average or low margins
👉 Big customers are not always the most profitable.

3️⃣ Best customers are top-right

Customers with high revenue and high margin are fewer but most valuable
👉 These should be protected and prioritized.

4️⃣ Low-margin risk zone exists

Customers below the horizontal line (low margin) still generate revenue
👉 Likely discount-heavy or high-cost customers.

5️⃣ Upsell opportunity

Customers with good margin but lower revenue (top-left)
👉 Strong candidates for upselling and growth.
"""

# Select numeric columns only
numeric_df = df.select_dtypes(include=['int64', 'float64'])

corr_matrix = numeric_df.corr()
plt.figure(figsize=(12, 8))

ax = sns.heatmap(
    corr_matrix,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    center=0,
    linewidths=0.5
)

ax.set_title('Correlation Heatmap of Numeric Features')

plt.tight_layout()
plt.show()

cols = [
    'order_quantity',
    'unit_price',
    'revenue',
    'total_cost',
    'Profit'
]

numeric_df = df[cols]

corr_matrix = numeric_df.corr()

plt.figure(figsize=(8, 6))

ax = sns.heatmap(
    corr_matrix,
    annot=True,
    fmt='.2f',
    cmap='coolwarm',
    center=0,
    linewidths=0.5
)

ax.set_title('Correlation Heatmap: Sales & Cost Metrics')

plt.tight_layout()
plt.show()

"""1️⃣ Revenue depends more on price than quantity

Unit price has a very strong impact on revenue.

Order quantity has a much weaker impact.
👉 Increasing prices matters more than selling more units.

2️⃣ Costs grow almost directly with revenue

When revenue increases, total cost also increases almost at the same rate.
👉 Scaling sales alone will not automatically improve margins.

3️⃣ Profit is driven by revenue, but costs reduce it

Higher revenue usually means higher profit,

but high costs reduce the benefit.
👉 Revenue growth without cost control is risky.

4️⃣ Selling more units doesn’t guarantee more profit

Order quantity has a weak link with profit.
👉 Bulk or high-volume sales are likely low-margin.

5️⃣ Unit price is the strongest lever

It strongly affects revenue, cost, and profit.
👉 Poor pricing or heavy discounting will quickly hurt profitability.
"""

df.head(5)

# save new df
df.to_csv('NEW_MAIN.csv', index=False)

